@startuml

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

abstract class AbstractQueuedSynchronizer{
lock()
tryLock()
unlock()
isLocked()
}
interface Runnable{
run()
}
class Worker{
        Thread thread
        Runnable firstTask
        run()
        lock()
        tryLock()
        unlock()
        isLocked()
}

AbstractQueuedSynchronizer <|-- Worker
Runnable <|- Worker

@enduml